name: Packer Validation Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  packer_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Check Packer format
        run: |
          packer init packer.pkr.hcl
          packer fmt -check packer.pkr.hcl

      - name: Validate Packer template
        run: |
          packer validate \
          -var 'project_id=${{ secrets.PROJECT_ID }}' \
          -var 'gcp_zone=${{ secrets.GCP_ZONE }}' \
          -var 'source_image=${{ secrets.SOURCE_IMAGE }}' \
          -var 'ssh_username=${{ secrets.SSH_USERNAME }}' \
          packer.pkr.hcl
