name: Packer Build Workflow

on:
  push:
    branches:
      - main
jobs:
  Artifact_Config_Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Decode JSON secret
        run: |
          echo "${{ secrets.SERVICE_AUTH }}" | base64 --decode > data.json
          cat data.json

      - name: Decode Monitor auth JSON secret
        run: |
          echo "${{ secrets.MONITOR_AUTH }}" | base64 --decode > data.json
          cat monitor_auth.json
        

      - name: Zip project
        run: |
          zip -r webapp.zip .
        working-directory: ../
        id: zip

      - name: Set output variable
        run: echo "WEBAPP_ZIP_PATH=/home/runner/work/webapp/webapp.zip" >> $GITHUB_ENV

      - name: Print WEBAPP_ZIP_PATH
        run: echo "WEBAPP_ZIP_PATH=${{ env.WEBAPP_ZIP_PATH }}"

      - name: List contents of the directory
        run: |
            cd /home/runner/work/webapp/webapp
            ls -la

      - name: Run Packer build
        run: |
          packer init packer.pkr.hcl
          packer build --force \
          -var 'auth_file=data.json' \
          -var 'monitor_auth=monitor_auth.json' \
          -var 'project_path=/home/runner/work/webapp/webapp.zip' \
          -var 'project_id=${{ secrets.PROJECT_ID }}' \
          -var 'gcp_region=${{ secrets.GCP_REGION }}' \
          -var 'gcp_zone=${{ secrets.GCP_ZONE }}' \
          -var 'gcp_profile=${{ secrets.GCP_PROFILE }}' \
          -var 'source_image=${{ secrets.SOURCE_IMAGE }}' \
          -var 'ssh_username=${{ secrets.SSH_USERNAME }}' \
          packer.pkr.hcl