name: Packer Validation Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  packer_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Check Packer format
        run: |
          packer fmt -check packer.pkr.hcl
          exit_code=$?
          if [ $exit_code -eq 1 ]; then
            echo "Packer format check failed. Exiting..."
            exit 1
          fi
      - name: Validate Packer template
        run: packer validate packer.pkr.hcl
